cookie:
  expiry_days: 1
  key: login_cookie_key
  name: login_cookie_name
credentials:
  usernames:
    a:
      email: chientranminh0511@gmail.com
      name: a
      password: $2b$12$h//gZ799Puv1.3Xx4L4Ig.8cc9XJroON4ei2VQ2Ufled8n3Lz4ZFC
    admin:
      email: admin@gmail.com
      name: admin
      password: $2b$12$0DL83PN0ElcB8nFqSnUxueY9LC4vhdMA6G4cUfZ5ynzpz6YE55Chi
    shinichien:
      email: shinichien@gmail.com
      name: shinichien
      password: $2b$12$MGPS8zDt392dqPqNhQNkUud6gFZscUQxHwvG0010/sw4uRdW66fOO
preauthorized:
  emails:
  - admin@gmail.com
  - shinichien@gmail.com
accounts:
  a: developer
  admin: owner
  shinichien: reviewer
permissions:
  developer:
  - read
  - insert
  - update
  - delete
  - search
  ower:
  - read
  - insert
  - update
  - delete
  - search
  reviewer:
  - read
  - search
